apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oaw0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-oaw0@sha256:c9b94bd29b3f76b41d507fc4db5bb19449eab0c9f9c98a6a62c2bd50bef6f418
        name: my-nodejs
        resources: {}
status: {}
